.\" Process this file with
.\" groff -man -Tascii dMagneticini.5
.\"
.
.Dd December 27th, 2019
.Os OpenBSD 
.Dt dMagneticini 5
.
.Sh NAME
.Nm dMagnetic.ini
.Nd Configuration file for dMagnetic.
.
.
.Sh SHORTCUT
Run dMagnetic -helpini to see an example.
.Sh SYNOPSIS
The configuration for 
.Xr dMagnetic 1
, and the location of the game binaries is stored in a .ini file.
.Sh ELEMENTS
The elements within the .ini files are
.Bl -tag -width 10
.It Sections 
Sections are in square brackets.
.Pp
[FILE]
.Pp
[DEFAULTGUI]
.
.It Entries  
entries have a = in them.
.Pp
rows=40
.Pp
pawnmag=/usr/local/share/games/magneticscrolls/pawn.mag
.
.It Comments 
;This is a comment
.Pp
.
Comments start with a ;
.Pp
To use a ; in an entry, it has to be preceded by a backslash
\\;
.br
Consequently, using a backslash requires preceding it with a backslash as well.
\\\\
.Pp
.El
.Sh SECTION [FILE]
Like any .ini file, it is broken down into sections, each section contains entries. One section has to be [FILES]. It should contain the names of the game binaries, so that the game engine can find them.
For example:
.br
[FILES]
.br
pawnmag=/usr/local/share/games/magneticscrolls/pawn.mag
.br
pawngfx=/home/games/magneticscrolls/pawn.gfx
.br
;pawnmsdos=/home/games/magneticscrolls/msdosversions/PAWN
.Pp
The .mag and .gfx packages can be downloaded from https://msmemorial.if-legends.org/memorial.php, btw. If you are lucky enough to have a copy of the MSDOS version stored on your harddrive, you can provide the directory with the pawnmsdos entry.
.
.Sh SECTION [RANDOM]
This section configures the random number generator.
.Pp
.br
mode=pseudo
.br
;mode=real
.br
seed=12345
.Pp
The mode can be one of two: "pseudo" or "real". Each one of them offers a different experience whilst playing. When testing the software, or playing with scripts, the "pseudo" option should be chosen. This offers a certain degree of determinsm.
.br
Legal values for seed are in the range of 1 to 2147483647.
.Pp
.Sh SECTION [DEFAULTGUI]
This section is configuring the default output Interface. 
.Pp
.br
[DEFAULTGUI]
.br
rows=40
.br
columns=100
.br
;align=left
.br
align=block
.br
;align=right
.br
;mode=none
.br
;mode=monochrome
.br
;mode=low_ansi
.br
mode=high_ansi
.br
;mode=high_ansi2
.br
low_ansi_characters=\\\\/=|\\;
.br
monochrome_characters= .:-=+*x#@$X
.Pp
Changing the numbers of rows will make pictures longer, changing the number of columns makes them wider. To change the output mode, comment it in, and comment the current one out.
.br
The characters that will be used in the low ansi rendering mode can be configured with the low_ansi_characters entry. Note that the backslash and semicolon need to be escaped.
.br
The monochrome_characters entry is a the actual shade that will be displayed. The leftmost part start with the lowest intensity, it goes up until the right.
.Sh EXAMPLE
.Pp
;you can download the files from https://msmemorial.if-legends.org/magnetic.php
.br
[FILES]
.br
pawnmag=/usr/local/share/games/magneticscrolls/pawn.mag
.br
pawngfx=/usr/local/share/games/magneticscrolls/pawn.gfx
.br
;pawnmsdos=/usr/local/share/games/magneticscrolls/msdosversions/PAWN
.br
guildmag=/usr/local/share/games/magneticscrolls/guild.mag
.br
guildgfx=/usr/local/share/games/magneticscrolls/guild.gfx
.br
;guildmsdos=/usr/local/share/games/magneticscrolls/msdosversions/GUILD
.br
jinxtermag=/usr/local/share/games/magneticscrolls/jinxter.mag
.br
jinxtergfx=/usr/local/share/games/magneticscrolls/jinxter.gfx
.br
corruptionmag=/usr/local/share/games/magneticscrolls/ccorrupt.mag
.br
corruptiongfx=/usr/local/share/games/magneticscrolls/ccorrupt.gfx
.br
fishmag=/usr/local/share/games/magneticscrolls/fish.mag
.br
fishgfx=/usr/local/share/games/magneticscrolls/fish.gfx
.br
mythmag=/usr/local/share/games/magneticscrolls/myth.mag
.br
mythgfx=/usr/local/share/games/magneticscrolls/myth.gfx
.br
wonderlandmag=/usr/local/share/games/magneticscrolls/wonder.mag
.br
wonderlandgfx=/usr/local/share/games/magneticscrolls/wonder.gfx
.br
.br
.br
[RANDOM]
.br
mode=pseudo
.br
;mode=real
.br
seed=12345
.br
.br
.br
[DEFAULTGUI]
.br
rows=40
.br
columns=120
.br
;align=left
.br
align=block
.br
;align=right
.br
;mode=none
.br
;mode=monochrome
.br
;mode=low_ansi
.br
mode=high_ansi
.br
;mode=high_ansi2
.br
low_ansi_characters=Thomas
.br
monochrome_characters= .-=+*x#@$X
.Pp
.Sh BUGS
Report bugs to
.An Aq dettus@dettus.net .
Make sure to include DMAGNETIC somewhere in the subject.
.Sh AUTHOR
Written by
.An Thomas Dettbarn
.Sh SEE ALSO
.Xr dMagnetic 1
